### ISSUE TITLE
Tags for jupyterhub versions

### ISSUE THREAD

**Issue by kafonek** [nbgallery/docker-images#12]
When JupyterHub is spawning single user processes as containers (such as `docker-stacks` image), the downstream process needs to have jupyterhub with a matching version as the upstream Hub that did the spawning.

The [jupyter/base-notebook](https://hub.docker.com/r/jupyter/base-notebook/tags) DockerHub profile has tags for specific jupyterhub versions (e.g. [hub-1.0.0](https://hub.docker.com/layers/jupyter/base-notebook/hub-1.0.0/images/sha256-c2306d463f3628a4825b282e7f0867814df71b620f31ad7d6f4cbd54365729f7?context=explore)).  Could we please create tags for `nbgallery/base-notebook` that are building from `jupyter/base-notebook` with the appropriate Hub tags.

That will ultimately make it much easier for JupyterHub deployments to use DockerSpawner and `nbgallery/base-notebook` for integrating with NBGallery.

**Comment by jeffyjefflabs** [comment]
To clarify, are you just suggesting we tag each release of `nbgallery/base-notebook` with whatever version of Hub it happens to contain (which is what `jupyter/base-notebook` appears to do, [based on the timestamps](https://hub.docker.com/r/jupyter/base-notebook/tags?page=1&name=hub)) (easy), or are you suggesting we maintain multiple builds containing our latest changes on top of multiple older upstream images (harder)?  I prefer the former not only because it's easier but also because it encourages users to keep their Hub up to date.

**Comment by kafonek** [comment]
@jeffyjefflabs I think the former, they appear to have CI in place to set multiple tags here https://github.com/jupyter/docker-stacks/blob/master/base-notebook/hooks/apply_tags

**Comment by jeffyjefflabs** [comment]
I don't know if you still need this, but I added a script based on the upstream CI (which moved to [here](https://github.com/jupyter/docker-stacks/blob/master/base-notebook/hooks/run_hook)).  I don't want to setup CI at the moment so it's manual for now, but results are on [docker hub](https://hub.docker.com/r/nbgallery/base-notebook/tags?page=1&ordering=last_updated).

**Comment by mcrutch** [comment]
Can't do CI, script takes care of this, closing the ticket.
