### ISSUE TITLE
Change Allow-Origin value

### ISSUE THREAD

**Issue by haha150** [nbgallery/docker-images#9]
Hello,

So i have tried to change the field: 
c.JupyterApp.allow_origin = nbgallery_url

in the jupyter_notebook_config.py to:
c.JupyterApp.allow_origin = '*'

To ensure that requests can come from anywhere, but this doesnt work when i do "run in jupyter" in nbgallery side.

Do you know if it is possible to set "*" there in any way?

**Comment by jeffyjefflabs** [comment]
Apparently wildcard cannot be used in conjunction with `withCrendentials: true` ([ref](https://stackoverflow.com/questions/19743396/cors-cannot-use-wildcard-in-access-control-allow-origin-when-credentials-flag-i)).  However I just tried `c.JupyterApp.allow_origin_pat = '.*'` instead and that seems to work fine - it works by just echoing back the client-provided Origin, instead of `'*'`.

Another thing we've seen before that might be worth checking - if you have a proxy involved, it may not be passing the various origin headers through.

**Comment by haha150** [comment]
Thanks.

Does this that i should keep:
`c.JupyterApp.allow_origin = nbgallery_url`

and add :
`c.JupyterApp.allow_origin_pat = '.*'`

**Comment by haha150** [comment]
After further testing, i had to use the following:
```
//c.JupyterApp.allow_origin = nbgallery_url
c.JupyterApp.allow_origin_pat = '.*'
```

**Comment by jeffyjefflabs** [comment]
Yes, `allow_origin` takes precedence over `allow_origin_pat` ([code](https://github.com/jupyter/notebook/blob/70d74d21ac051fbeaa81d4ef4fff9fa759de96d7/notebook/notebookapp.py#L621)).  Out of curiosity, why do you need to support multiple origins?  Do you have multiple nbgallery instances or some other system interacting with Jupyter via CORS?

**Comment by haha150** [comment]
Yes we have one other system that is talking to the Jupyter server.
